config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :content, length: { in: 1..2200 }
  validates :image, presence: true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures
  has_many :favorites, dependent: :destroy
  mount_uploader :user_image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
  private
  def logged_in_user
    unless logged_in?
      redirect_to new_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = Favorite.create(picture_id: params[:picture_id], user_id: current_user.id)
    redirect_to pictures_path
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    url = request.referer
    redirect_to url
  end
  def index
    if current_user == nil
      redirect_to new_session_path
    else
      @user_favorites = current_user.favorites
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :show, :edit, :update, :destroy]
  def index
    @pictures = Picture.all.order(id: "DESC")
    @users = User.all
  end
  def new
    @picture = Picture.new
  end
  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      respond_to do |format|
        if @picture.save
          PictureMailer.picture_mail(@picture).deliver
          format.html { redirect_to pictures_path, notice: '投稿しました' }
          format.json { render :show, status: :created, location: @picture }
        else
          format.html { render :new }
          format.json { render json: @picture.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  def edit
  end
  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "投稿を編集しました"
    else
      render :edit
    end
  end
  def destroy
    @picture.delete
    redirect_to pictures_path, notice: '投稿を削除しました'
  end
  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end
  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  private
  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end
  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to pictures_path
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :logged_in_user, only: [:show, :edit, :update]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path, notice: 'アカウントが作成されました！'
    else
      render :new
    end
  end
  def show
    if @user.id == current_user.id
    else
      redirect_to new_session_path
    end
  end

  def edit
    if @user.id == current_user.id
    else
      redirect_to new_session_path
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: 'プロフィールを編集しました'
    else
      render :edit
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile, :user_image)
  end
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.slim
nav.head.navbar.bg-light.border
  .container
    .row
      .col-xs-1
        h2.title instaclone
    .row
      .icon
        = link_to image_tag('camera.png', class:'header-img'), new_picture_path
        = link_to image_tag('momo.png', class:'header-img'), pictures_path
        = link_to image_tag('heart2.png', class:'header-img'), favorites_path
        = link_to image_tag('person.png', class:'header-img'), user_path(current_user.id)
        = link_to image_tag('logout.png', class:'header-img'), session_path(current_user.id), method: :delete, data: { confirm: 'ログアウトしますか？' }


.container

  .big_container

    h4.fav_title #{@current_user.name}さんのお気に入り一覧

    .row

      - @user_favorites.each do |favorite|

        .col-lg-4.col-md-4.col-xs-4

          .row

            = image_tag favorite.picture.image.url ,class:'col-sm-12'

          .row
            = link_to image_tag('heart1.png', class:'fav_mark'), favorite_path(id: favorite.id), :method => :delete, data: { confirm: '本当にお気に入り解除していいですか？' }


footer.container

  p.row.justify-content-end made by Jun Yamada

app/views/layouts/application.html.slim
DOCTYPE
html
  head
    title Instaclo
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body

= yield

app/views/pictures/_footer.html.slim
footer.container

  p.row.justify-content-end made by Jun Yamada

app/views/pictures/_header.html.slim
nav.head.navbar.bg-light.border
  .container
    .row
      .col-sm-1
        h2.title instaclone
    .row
      .icon
        - if current_user == nil
          = link_to image_tag('camera.png', class:'header-img'), new_user_path
          = link_to image_tag('momo.png', class:'header-img'), pictures_path
          = link_to image_tag('heart2.png', class:'header-img'), new_user_path
          = link_to image_tag('person.png', class:'header-img'), new_user_path
          = link_to image_tag('logout.png', class:'header-img'), new_session_path

        - else
          = link_to image_tag('camera.png', class:'header-img'), new_picture_path
          = link_to image_tag('momo.png', class:'header-img'), pictures_path
          = link_to image_tag('heart2.png', class:'header-img'), favorites_path
          = link_to image_tag('person.png', class:'header-img'), user_path(current_user.id)
          = link_to image_tag('logout.png', class:'header-img'), session_path(current_user.id), method: :delete, data: { confirm: 'ログアウトしますか？' }

app/views/pictures/confirm.html.slim
= render 'header'

.container

  p 確認

  .index_container.big_container

    = form_with(model: @picture, local: true) do |f|
      = f.hidden_field :image_cache
      = f.hidden_field :content

      div.row

        = image_tag @picture.image.url, class:'col-xs-1 col-md-12'

        p.col-xs-12.col-md-12 = @picture.content

          | = @picture.content


      = f.submit  "送信", class: "btn btn-success"
      = f.submit  "戻る", name: 'back', class: "btn btn-info"

  = render 'footer'

app/views/pictures/edit.html.slim
= render 'header'

.container
  .container.border.new_form_container.big_container
    h4.title edit
    .row.justify-content-center
      = form_with(model: @picture, local: true) do |f|

        - if @picture.errors.any?
          div#error_explanation
            p
              ul
              - @picture.errors.full_messages.each do |msg|
                li.alert.alert-warning.post_error = msg

        .field
          = f.file_field :image

        .insta
          = f.text_area :content, class: 'textarea'

          = f.submit '編集', class: 'btn btn-secondary'

          =link_to '一覧に戻る', pictures_path, class: 'btn btn-info'

  = render 'footer'

app/views/pictures/index.html.slim
= render 'header'

.container

  .row.justify-content-center

    - if notice == nil

      p
    - else

      .alert.alert-primary.index_alert = notice

.container.big_container

  - if current_user == nil

    .row
      .col-lg-5.offset-lg-6.offset-md-7.user_info.index_prof

        .row

          form.login_form
            p あなたも始めませんか？
            .w-100
            = link_to 'アカウント作成画面へ', new_user_path

    - @pictures.each do |pic|
      .index_container.col-lg-8.border
        .row.border-bottom.post_user
          - if pic.user.user_image.url == nil
            = image_tag 'person.png', class:'index_icon'
          - else
            = image_tag pic.user.user_image.url, class:'index_icon'

          h5.col-md-9.col-sm-8.upuser_name #{pic.user.name}
        = image_tag pic.image.url, class:'index_img border-bottom'

        .row.border-top.index_comment
          = pic.content

  - else

    .row
      .col-lg-5.offset-lg-6.offset-md-7.user_info.index_prof

        .row

          - if current_user.user_image.url == nil

            = image_tag 'person.png', class:'col-lg-2 index_prof_img'

          - else

            = image_tag current_user.user_image.url, class:'col-lg-2 index_prof_img'


          h5.col-lg-4.user_name #{current_user.name}

          = link_to '編集する', edit_user_path(id: current_user.id), class: "btn btn-light col-sm-6 col-md-4 col-lg-2 prof_edit_btn border border-dark"

          p.col-lg-8.index_prof_content #{current_user.profile}


    - @pictures.each_with_index do |pic,idx|
      - fav = Favorite.find_by(user_id: current_user.id, picture_id: pic.id)
      .index_container.col-lg-8.border
        .row.border-bottom.post_user
          - if pic.user.user_image.url == nil
            = image_tag 'person.png', class:'index_icon'
          - else
            = image_tag pic.user.user_image.url, class:'index_icon'

          h5.col-md-9.col-sm-8.upuser_name #{pic.user.name}
        = image_tag pic.image.url, class:'index_img border-bottom'

        li
          - if current_user.id == pic.user_id
            - if fav == nil
              = link_to image_tag('heart2.png', class:'header-img'),favorites_path(picture_id: pic.id), method: :post
            - else
              = link_to image_tag('heart1.png', class:'header-img'), favorite_path(id: fav.id),  :method => :delete
            =link_to image_tag('edit.png', class:'header-img'), edit_picture_path(pic.id)
            =link_to image_tag('del.png', class:'header-img'), picture_path(pic.id),  :method => :delete ,data: { confirm: '本当に削除していいですか？' }
          - else
            -if fav == nil
              = link_to image_tag('heart2.png', class:'header-img'),favorites_path(picture_id: pic.id), method: :post
            -else
              = link_to image_tag('heart1.png', class:'header-img'), favorite_path(id: fav.id),  :method => :delete

        .row.border-top.index_comment
          = pic.content



= render 'footer'

app/views/pictures/new.html.slim
= render 'header'

.container
  .container.border.new_form_container.big_container
    h4.title post
    .row.justify-content-center
      = form_with(model: @picture, local: true, url:confirm_pictures_path) do |f|

        - if @picture.errors.any?
          div#error_explanation
            p
              ul
              - @picture.errors.full_messages.each do |msg|
                li.alert.alert-warning.post_error = msg

        .field
          = f.file_field :image

        .insta
          = f.text_area :content , class: 'textarea'

        = f.submit '確認', class: 'btn btn-secondary'

  = render 'footer'

app/views/pictures/show.html.slim
p hello

app/views/users/_footer.html.slim
footer.container

  p.row.justify-content-end made by Jun Yamada

app/views/users/_header.html.slim
nav.head.navbar.bg-light.border
  .container
    .row
      .col-sm-1
        h2.title instaclone
    .row
      .icon
        = link_to image_tag('camera.png', class:'header-img'), new_picture_path
        = link_to image_tag('momo.png', class:'header-img'), pictures_path
        = link_to image_tag('heart2.png', class:'header-img'), favorites_path
        = link_to image_tag('person.png', class:'header-img'), user_path(current_user.id)
        = link_to image_tag('logout.png', class:'header-img'), session_path(current_user.id), method: :delete, data: { confirm: 'ログアウトしますか？' }

app/views/users/edit.html.slim
= render 'header'



.container.border.prof_edit_container.big_container
  .row
    .col-xs-4.offset-4
      = form_with(model: @user, local: true) do |f|
        div.field
          - if @user.user_image.url == nil

            li = image_tag 'person.png', class:'prof_img col-xs-3'
            li = f.file_field :user_image
          - else

            li = image_tag @user.user_image.url, class:'ed_pic'
            li = f.file_field :user_image

        li = f.label :'名前(ニックネーム)'
        li = f.text_field :name
        li = f.label :'自己紹介'
        li = f.text_area :profile
        li = f.label :'メールアドレス'
        li = f.email_field :email
        li = f.label :'パスワードを入力してください'
        li = f.password_field :password
        = f.submit '送信する', class: 'btn btn-info btn_sousin'

  .row.justify-content-center
    = link_to "プロフィールに戻る", user_path(current_user.id), class: "btn btn-dark btn_bottom"


= render 'footer'

app/views/users/new.html.slim
.container

  - if @user.errors.any?
    .row.justify-content-center
      .alert.alert-danger.alert_signup.col-lg-3
        ul
        - @user.errors.full_messages.each do |message|
          li.error_explanation = message

  .row.justify-content-center
    .form-wrapper.col-sm-12
      h3.title instaclone
      = form_with(model: @user, local: true) do |f|

        .form-item
          = f.text_field :name, placeholder: 'name'

        .form-item
          = f.email_field :email, placeholder: 'email'

        .form-item
          = f.password_field :password, placeholder: 'password'

        .form-item
          = f.password_field :password_confirmation, placeholder: 'password_confirmation'

        .button-panel
          input.button[type="submit" title="signup" value="登録"]

  .row.justify-content-center
    .form-wrapper.signup.col-sm-12
      form
        p アカウントを持っている方は
        =link_to 'ログイン', new_session_path

= render 'footer'

app/views/users/show.html.slim
= render 'header'


.container.prof_cont.big_container

  .row
    - if @user.user_image.url == nil

      = image_tag 'person.png', class:'col-xs-2 prof_img'

    - else

      = image_tag @user.user_image.url, class:'col-xs-2 prof_img'


    .row.col-sm-8.col-md-9.col-lg-10
      h2.col-sm-6.col-md-8.col-lg-9.user_name #{@user.name}

      = link_to 'プロフィール編集', edit_user_path, class: "btn btn-light col-sm-6 col-md-4 col-lg-3 prof_edit_btn border border-dark"

      .w-100

      p.col-xs-10.prof_content #{@user.profile}

.container

  .row.justify-content-center

    - if notice == nil

      p
    - else

      .alert.alert-success.prof_alert = notice





  = render 'footer'